name: Flutter - Android Build apk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get




      - name: User Build APK
        run: flutter build apk --dart-define=APP_ROLE=user

      - name: Upload User APK
        uses: actions/upload-artifact@v4
        with:
          name: release-flutter-apk-user
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Driver Build APK
        run: flutter build apk --release --dart-define=APP_ROLE=driver

      
      - name: Upload Driver APK
        uses: actions/upload-artifact@v4
        with:
          name: release-flutter-apk-driver
          path: build/app/outputs/flutter-apk/app-release.apk





        